#!/usr/bin/python3
import sys
import cgi
import random
import os
import tempfile
from http import cookies
#debugging
#import cgitb; cgitb.enable()

def die(s):
    print("Content-Type: text/html")
    print("")
    print("""<html>
  <head>
    <title>Password Storage</title>
  </head>
  <body>
%s
  </body>
</html>""" % s)
    sys.exit(0)


form = cgi.FieldStorage()

if "id" in form:
    id = form["id"].value;
else:
    id = ""
if "site" in form:
    site = form["site"].value;
else:
    site = ""
if "username" in form:
    username = form["username"].value;
else:
    username = ""
if "password" in form:
    password = form["password"].value;
else:
    password = ""
if "admin" in form:
    admin = form["admin"].value;
else:
    admin = "0"

debug = False
if debug:
    id = "foo1337"
    site = "www.bar.com"
    username = "john"
    password = "pazzword"
    admin = "1"

if (id == "" or site == "" or username == "" or password == ""):
    die("<p>Missing parameters.</p>")

if not id.isalnum():
    die("<p>Bad id.</p>")

if admin == "1":
    try:
        blacklist = cookies.SimpleCookie(os.environ['HTTP_COOKIE'])['blacklist'].value
    except Exception:
        die("<p>Malformed cookie or missing blacklist name</p>")
    if blacklist.isalnum() == False:
        die("<p>Bad blacklist name. It must be alphanumeric.</p>")
    try:
        f = open(blacklist, "r")
        m = f.read()
        f.close()
    except Exception as ex:
        die("<p>Cannot open blacklist file %s: %s</p>" % (blacklist, str(e)))

    die("<p>Blacklist:</p><pre>%s</pre>" % m)

try:
    f = open("/challenge/storage/" + id, "a+")
    f.write("%s:%s:%s\n" % (site, username, password))
    f.close()
except Exception as ex:
    die("<p>Something went horriby wrong (%s). Contact the admin.</p>" % str(e))

die("<p>Password saved.</p>")

